--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.845
--   Created On : 星期二, 14 八月, 2012 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 




--  Create Tables 
CREATE TABLE ReportDataParameter ( 
	RD_ID int NOT NULL,    --  报表模板ID 
	ParameterName varchar(50) NOT NULL,    --  参数名称 
	ParameterType smallint NOT NULL,    --  参数类型 
	ParameterLength int NOT NULL,    --  参数长度 
	ParameterValue varchar(500),    --  参数默认值 
	OrderID smallint DEFAULT ((0)),    --  参数加载序号 
	bz varchar(500),    --  备注 
	ParType smallint DEFAULT ((0)),
	DisplayMember varchar(50),
	ValueMember varchar(50),
	ConnectionString varchar(500),
	CommandType smallint,
	CommandText varchar(2000),
	Script varchar(2000),
	Items varchar(1000), 
    CONSTRAINT [PK_ReportDataParameter] PRIMARY KEY ([RD_ID], [ParameterName])
)